import './globals.scss';
import { DeviceProvider } from '@utils/context/deviceContext/DeviceProvider';
import { DeviceType } from '@appTypes/deviceType';
import { Footer } from '@components/Layouts/Footer';
import { Header } from '@components/Layouts/Header';
import { HeaderMobile } from '@components/Layouts/HeaderMobile';
import type { Metadata } from 'next';
import { QueryProvider } from '@utils/components/QueryProvider';
import { getDeviceType } from '@utils/lib/getDeviceType';
import localFont from 'next/font/local';

const openSans = localFont({
	src: [
		{
			path: '../public/fonts/OpenSans/OpenSans-Regular.woff2',
			weight: '400',
			style: 'normal',
		},
	],
	variable: '--open-sans',
});

const rubik = localFont({
	src: [
		{
			path: '../public/fonts/Rubik/Rubik-Light.woff2',
			weight: '300',
			style: 'normal',
		},
		{
			path: '../public/fonts/Rubik/Rubik-Medium.woff2',
			weight: '500',
			style: 'normal',
		},
	],
	variable: '--rubik',
});
const firaSans = localFont({
	src: [
		{
			path: '../public/fonts/FiraSansCondensed/FiraSansCondensed-Light.woff2',
			weight: '300',
			style: 'normal',
		},
		{
			path: '../public/fonts/FiraSansCondensed/FiraSansCondensed-Regular.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../public/fonts/FiraSansCondensed/FiraSansCondensed-Medium.woff2',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../public/fonts/FiraSansCondensed/FiraSansCondensed-SemiBold.woff2',
			weight: '600',
			style: 'normal',
		},
	],
	variable: '--font-fira-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const deviceType = await getDeviceType();

	return (
		<html lang='ru'>
			<body className={`${openSans.className} ${rubik.className} ${firaSans.className}`}>
				<QueryProvider>
					<DeviceProvider deviceType={deviceType}>
						{deviceType === DeviceType.Desktop ? <Header className='header' /> : <HeaderMobile />}
						<main className='main'>{children}</main>
						<Footer className='footer' />
					</DeviceProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
